### //Test método obtenerServicios
GET http://localhost:3000/api/volquetes


### //Test método obtenerServicio
GET http://localhost:3000/api/volquetes/649fd21745481facccfb1d9d

### //Test método crearSolicitudVolquete
POST http://localhost:3000/api/volquetes
Content-Type: application/json

{
    "numero": 12349,
    "cliente": "Salvador",
    "precio": 99232,
    "cantidad":2,
    "tamanio":"grande",
    "chofer":"Matías",
    "ubicacion": "Cuenca 2851"
}

### //Test método eliminar

DELETE http://localhost:3000/api/volquetes/649fcaba0199c22fb92dd953